import { Medication } from '../types';

/**
 * Référentiel Officiel Hors-Ligne des Médicaments les plus prescrits au Maroc
 * Inclut: DCI, Dosage, Forme galénique, Laboratoire, Posologie usuelle et Tarification indicative PPV (DH)
 */
export const MOROCCAN_MEDICATIONS_CATALOG: Medication[] = [
  // ==========================================
  // ANTALGIQUES & ANTIPYRÉTIQUES
  // ==========================================
  {
    id: 'mar_med_1',
    name: 'Doliprane 1000 mg',
    dci: 'Paracétamol',
    dosage: '1000 mg',
    category: 'Antalgique / Antipyrétique',
    dosageForm: 'Comprimé',
    laboratory: 'Sanofi-Aventis Maroc',
    defaultDosage: '1 comprimé toutes les 6 à 8 heures si douleur (max 3 à 4g/jour)',
    defaultDuration: '3 à 5 jours',
    defaultInstructions: 'À avaler avec un grand verre d’eau. Ne pas associer à un autre médicament contenant du paracétamol.',
    contraindications: 'Insuffisance hépatocellulaire sévère, hypersensibilité au paracétamol.',
    sideEffects: 'Rares réactions cutanées allergiques, élévation des transaminases en surdosage.',
    unitPrice: 15.6,
    presentation: 'Boîte de 8 comprimés',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_2',
    name: 'Doliprane 500 mg',
    dci: 'Paracétamol',
    dosage: '500 mg',
    category: 'Antalgique / Antipyrétique',
    dosageForm: 'Gélule',
    laboratory: 'Sanofi-Aventis Maroc',
    defaultDosage: '1 à 2 gélules toutes les 6 heures (max 3g/jour)',
    defaultDuration: '3 à 5 jours',
    defaultInstructions: 'Prise orale avec un verre d’eau en respectant un intervalle minimal de 4 heures.',
    contraindications: 'Insuffisance hépatique sévère.',
    unitPrice: 11.2,
    presentation: 'Boîte de 16 gélules',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_3',
    name: 'Doliprane Sirop 2.4%',
    dci: 'Paracétamol',
    dosage: '2.4% (pédiatrique)',
    category: 'Antalgique / Antipyrétique',
    dosageForm: 'Sirop / Suspension buvable',
    laboratory: 'Sanofi-Aventis Maroc',
    defaultDosage: '1 dose-kilo (pipette graduée en kg) toutes les 6 heures si fièvre/douleur',
    defaultDuration: '3 à 5 jours',
    defaultInstructions: 'Bien agiter le flacon avant emploi. Utiliser exclusivement la pipette doseuse fournie.',
    contraindications: 'Insuffisance hépatique sévère, phénylcétonurie.',
    unitPrice: 14.5,
    presentation: 'Flacon de 100 ml avec pipette doseuse graduée en kg',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_4',
    name: 'Doliprane 150 mg Suppositoire',
    dci: 'Paracétamol',
    dosage: '150 mg',
    category: 'Antalgique / Antipyrétique',
    dosageForm: 'Suppositoire',
    laboratory: 'Sanofi-Aventis Maroc',
    defaultDosage: '1 suppositoire 3 à 4 fois par jour (nourrisson de 8 à 12 kg)',
    defaultDuration: '3 jours',
    defaultInstructions: 'Voie rectale. Espacer les prises de 6 heures.',
    contraindications: 'Lésions ano-rectales récentes, insuffisance hépatique.',
    unitPrice: 10.8,
    presentation: 'Boîte de 10 suppositoires',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_5',
    name: 'Doliprane 300 mg Suppositoire',
    dci: 'Paracétamol',
    dosage: '300 mg',
    category: 'Antalgique / Antipyrétique',
    dosageForm: 'Suppositoire',
    laboratory: 'Sanofi-Aventis Maroc',
    defaultDosage: '1 suppositoire 3 à 4 fois par jour (enfant de 13 à 20 kg)',
    defaultDuration: '3 jours',
    defaultInstructions: 'Voie rectale. Espacer les prises de 6 heures.',
    contraindications: 'Lésions ano-rectales récentes, insuffisance hépatique.',
    unitPrice: 12.0,
    presentation: 'Boîte de 10 suppositoires',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_6',
    name: 'Efferalgan 1 g Effervescent',
    dci: 'Paracétamol',
    dosage: '1000 mg',
    category: 'Antalgique / Antipyrétique',
    dosageForm: 'Comprimé effervescent',
    laboratory: 'UPSA / Maphar Maroc',
    defaultDosage: '1 comprimé dissous dans un verre d’eau 3 fois par jour',
    defaultDuration: '3 à 5 jours',
    defaultInstructions: 'Dissoudre complètement dans un grand verre d’eau avant consommation.',
    contraindications: 'Insuffisance hépatique, régime sans sel strict (contient du sodium).',
    unitPrice: 18.2,
    presentation: 'Boîte de 8 comprimés effervescents',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_7',
    name: 'Dafalgan 1 g',
    dci: 'Paracétamol',
    dosage: '1000 mg',
    category: 'Antalgique / Antipyrétique',
    dosageForm: 'Comprimé pelliculé',
    laboratory: 'UPSA / Maphar Maroc',
    defaultDosage: '1 comprimé toutes les 6 heures si besoin (max 4 comprimés/jour)',
    defaultDuration: '3 à 5 jours',
    defaultInstructions: 'Prendre avec un verre d’eau.',
    contraindications: 'Insuffisance hépatocellulaire sévère.',
    unitPrice: 17.5,
    presentation: 'Boîte de 8 comprimés',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_8',
    name: 'Panadol 500 mg',
    dci: 'Paracétamol',
    dosage: '500 mg',
    category: 'Antalgique / Antipyrétique',
    dosageForm: 'Comprimé pelliculé',
    laboratory: 'GlaxoSmithKline (GSK) Maroc',
    defaultDosage: '1 à 2 comprimés toutes les 4 à 6 heures (max 4g/jour)',
    defaultDuration: '3 à 5 jours',
    defaultInstructions: 'Voie orale.',
    contraindications: 'Insuffisance hépatique sévère.',
    unitPrice: 13.0,
    presentation: 'Boîte de 20 comprimés',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_9',
    name: 'Aspegic 1000 mg',
    dci: 'Acétylsalicylate de lysine (Aspirine)',
    dosage: '1000 mg',
    category: 'Antalgique / Anti-inflammatoire',
    dosageForm: 'Poudre pour solution buvable en sachet',
    laboratory: 'Sanofi-Aventis Maroc',
    defaultDosage: '1 sachet 3 fois par jour au cours des repas',
    defaultDuration: '3 à 5 jours',
    defaultInstructions: 'Dissoudre le contenu du sachet dans un demi-verre d’eau ou de jus.',
    contraindications: 'Ulcère gastro-duodénal évolutif, hémophilie, allergie à l’aspirine, grossesse T3.',
    unitPrice: 22.5,
    presentation: 'Boîte de 15 sachets-doses',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_10',
    name: 'Aspegic 500 mg',
    dci: 'Acétylsalicylate de lysine (Aspirine)',
    dosage: '500 mg',
    category: 'Antalgique / Antipyrétique',
    dosageForm: 'Poudre pour solution buvable en sachet',
    laboratory: 'Sanofi-Aventis Maroc',
    defaultDosage: '1 sachet 3 fois par jour au milieu des repas',
    defaultDuration: '3 à 5 jours',
    defaultInstructions: 'Prendre impérativement au cours d’un repas.',
    contraindications: 'Ulcère gastrique, risque hémorragique, varicelle chez l’enfant.',
    unitPrice: 16.8,
    presentation: 'Boîte de 20 sachets-doses',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_11',
    name: 'Aspegic Nourrisson 100 mg',
    dci: 'Acétylsalicylate de lysine (Aspirine)',
    dosage: '100 mg',
    category: 'Antalgique / Antiagrégant plaquettaire',
    dosageForm: 'Poudre pour solution buvable en sachet',
    laboratory: 'Sanofi-Aventis Maroc',
    defaultDosage: '1 sachet par jour ou selon avis médical spécialisé',
    defaultDuration: 'Selon indication',
    defaultInstructions: 'Diluer dans de l’eau ou un biberon tiède.',
    contraindications: 'Ulcère digestif, risque de syndrome de Reye.',
    unitPrice: 12.5,
    presentation: 'Boîte de 20 sachets',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },

  // ==========================================
  // ANTI-INFLAMMATOIRES NON STÉROÏDIENS (AINS)
  // ==========================================
  {
    id: 'mar_med_12',
    name: 'Voltarène 50 mg',
    dci: 'Diclofénac sodique',
    dosage: '50 mg',
    category: 'Anti-inflammatoire non stéroïdien (AINS)',
    dosageForm: 'Comprimé gastro-résistant',
    laboratory: 'Novartis Pharma Maroc',
    defaultDosage: '1 comprimé 2 à 3 fois par jour au milieu des repas',
    defaultDuration: '5 à 7 jours',
    defaultInstructions: 'Avaler sans croquer avec un verre d’eau pendant les repas.',
    contraindications: 'Ulcère gastro-duodénal actif, insuffisance cardiaque congestive, insuffisance rénale/hépatique sévère, 3ème trimestre de grossesse.',
    sideEffects: 'Épigastralgies, nausées, risque d’ulcère gastrique.',
    unitPrice: 31.2,
    presentation: 'Boîte de 30 comprimés',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_13',
    name: 'Voltarène 100 mg LP',
    dci: 'Diclofénac sodique',
    dosage: '100 mg LP',
    category: 'Anti-inflammatoire non stéroïdien (AINS)',
    dosageForm: 'Comprimé à libération prolongée',
    laboratory: 'Novartis Pharma Maroc',
    defaultDosage: '1 comprimé par jour le soir au milieu du repas',
    defaultDuration: '7 à 14 jours',
    defaultInstructions: 'Ne pas écraser ni croquer le comprimé LP.',
    contraindications: 'Ulcère gastroduodénal, cardiopathie ischémique, antécédent d’AVC.',
    unitPrice: 42.0,
    presentation: 'Boîte de 15 comprimés LP',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_14',
    name: 'Voltarène Emulgel 1%',
    dci: 'Diclofénac diéthylamine',
    dosage: '1%',
    category: 'Anti-inflammatoire local / Rhumatologie',
    dosageForm: 'Gel dermique',
    laboratory: 'Novartis / GSK Consumer Healthcare',
    defaultDosage: '1 application locale 3 fois par jour en massage doux',
    defaultDuration: '7 jours',
    defaultInstructions: 'Appliquer sur la zone douloureuse et masser jusqu’à pénétration. Se laver les mains après application.',
    contraindications: 'Peau lésée, plaies ouvertes, eczéma, brûlures.',
    unitPrice: 28.5,
    presentation: 'Tube de 50 g',
    reimbursementRate: 'Remboursable AMO',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_15',
    name: 'Profénid 100 mg',
    dci: 'Kétoprofène',
    dosage: '100 mg',
    category: 'Anti-inflammatoire non stéroïdien (AINS)',
    dosageForm: 'Comprimé pelliculé sécable',
    laboratory: 'Sanofi-Aventis Maroc',
    defaultDosage: '1 comprimé 2 fois par jour au milieu des repas',
    defaultDuration: '5 à 7 jours',
    defaultInstructions: 'Toujours associer à une prise alimentaire.',
    contraindications: 'Ulcère gastrique évolutif, insuffisance rénale, grossesse T3.',
    unitPrice: 38.6,
    presentation: 'Boîte de 30 comprimés',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_16',
    name: 'Bi-Profénid 150 mg',
    dci: 'Kétoprofène',
    dosage: '150 mg sécable',
    category: 'Anti-inflammatoire non stéroïdien (AINS)',
    dosageForm: 'Comprimé sécable à double couche',
    laboratory: 'Sanofi-Aventis Maroc',
    defaultDosage: '1 comprimé à 2 comprimés par jour au milieu des repas',
    defaultDuration: '5 à 7 jours',
    defaultInstructions: 'Prendre avec un grand verre d’eau au cours d’un repas.',
    contraindications: 'Ulcère peptique actif, antécédent d’asthme induit par AINS.',
    unitPrice: 56.4,
    presentation: 'Boîte de 20 comprimés sécables',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_17',
    name: 'Apranax 550 mg',
    dci: 'Naproxène sodique',
    dosage: '550 mg',
    category: 'Anti-inflammatoire non stéroïdien (AINS)',
    dosageForm: 'Comprimé pelliculé sécable',
    laboratory: 'Maphar Maroc / Roche',
    defaultDosage: '1 comprimé 1 à 2 fois par jour au cours des repas',
    defaultDuration: '5 à 7 jours',
    defaultInstructions: 'Prendre avec un grand verre d’eau pendant le déjeuner ou le dîner.',
    contraindications: 'Ulcère gastro-duodénal, insuffisance rénale sévère.',
    unitPrice: 48.3,
    presentation: 'Boîte de 16 comprimés',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_18',
    name: 'Advilex 400 mg (Advil)',
    dci: 'Ibuprofène',
    dosage: '400 mg',
    category: 'Anti-inflammatoire non stéroïdien (AINS)',
    dosageForm: 'Comprimé enrobé',
    laboratory: 'Laprophan Maroc',
    defaultDosage: '1 comprimé 3 fois par jour au milieu des repas (max 1200mg/jour)',
    defaultDuration: '3 à 5 jours',
    defaultInstructions: 'À prendre impérativement au cours d’un repas avec de l’eau.',
    contraindications: 'Ulcère gastrique ou duodénal en poussée, hémorragie digestive, grossesse T3.',
    unitPrice: 26.5,
    presentation: 'Boîte de 20 comprimés',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_19',
    name: 'Celebrex 200 mg',
    dci: 'Célécoxib',
    dosage: '200 mg',
    category: 'Anti-inflammatoire / Inhibiteur sélectif Cox-2',
    dosageForm: 'Gélule',
    laboratory: 'Pfizer Maroc',
    defaultDosage: '1 gélule par jour le matin au milieu du repas',
    defaultDuration: '10 à 15 jours',
    defaultInstructions: 'Prise orale au cours des repas.',
    contraindications: 'Cardiopathie ischémique avérée, artériopathie périphérique, AVC, allergie aux sulfamides.',
    unitPrice: 88.0,
    presentation: 'Boîte de 20 gélules',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_20',
    name: 'Surgam 200 mg',
    dci: 'Acide tiaprofénique',
    dosage: '200 mg',
    category: 'Anti-inflammatoire non stéroïdien (AINS)',
    dosageForm: 'Comprimé sécable',
    laboratory: 'Sanofi-Aventis Maroc',
    defaultDosage: '1 comprimé 2 fois par jour au cours des repas',
    defaultDuration: '5 à 7 jours',
    defaultInstructions: 'Prendre avec un verre d’eau au milieu des repas.',
    contraindications: 'Ulcère gastro-duodénal actif, antécédent de troubles vésicaux/urinaires récidivants.',
    unitPrice: 36.2,
    presentation: 'Boîte de 20 comprimés sécables',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },

  // ==========================================
  // CORTICOÏDES
  // ==========================================
  {
    id: 'mar_med_21',
    name: 'Solupred 20 mg',
    dci: 'Prednisolone',
    dosage: '20 mg',
    category: 'Corticoïde par voie générale',
    dosageForm: 'Comprimé orodispersible / effervescent',
    laboratory: 'Sanofi-Aventis Maroc',
    defaultDosage: '1 à 3 comprimés par jour en 1 seule prise le matin au petit-déjeuner',
    defaultDuration: '5 à 7 jours',
    defaultInstructions: 'Dissoudre dans un demi-verre d’eau ou laisser fondre dans la bouche. Prise le matin.',
    contraindications: 'Tout état infectieux non contrôlé, virose en évolution (hépatite, varicelle, herpès), psychose non contrôlée.',
    sideEffects: 'Excitation psychomotrice, insomnie, gastralgies, rétention hydrosodée.',
    unitPrice: 46.8,
    presentation: 'Boîte de 20 comprimés',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_22',
    name: 'Solupred 5 mg',
    dci: 'Prednisolone',
    dosage: '5 mg',
    category: 'Corticoïde par voie générale',
    dosageForm: 'Comprimé orodispersible',
    laboratory: 'Sanofi-Aventis Maroc',
    defaultDosage: 'Selon schéma dégressif ou avis pédiatrique (prise matinale)',
    defaultDuration: '5 à 7 jours',
    defaultInstructions: 'Prise le matin au cours du petit-déjeuner.',
    contraindications: 'États infectieux évolutifs non contrôlés.',
    unitPrice: 19.5,
    presentation: 'Boîte de 30 comprimés',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_23',
    name: 'Celestene 2 mg/ml Gouttes',
    dci: 'Bétaméthasone',
    dosage: '0.05% (2 mg / ml)',
    category: 'Corticoïde par voie générale',
    dosageForm: 'Solution buvable en gouttes',
    laboratory: 'Organon / Maphar Maroc',
    defaultDosage: '10 gouttes par kg et par jour en 1 prise le matin (max 40 gouttes/jour enfant)',
    defaultDuration: '3 à 5 jours',
    defaultInstructions: 'Diluer les gouttes dans un peu d’eau ou de jus sucré le matin.',
    contraindications: 'Infections bactériennes ou virales non contrôlées.',
    unitPrice: 28.0,
    presentation: 'Flacon compte-gouttes de 30 ml',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_24',
    name: 'Cortancyl 20 mg',
    dci: 'Prednisone',
    dosage: '20 mg',
    category: 'Corticoïde par voie générale',
    dosageForm: 'Comprimé sécable',
    laboratory: 'Sanofi-Aventis Maroc',
    defaultDosage: '1 à 2 comprimés le matin au petit-déjeuner',
    defaultDuration: '5 à 10 jours',
    defaultInstructions: 'Prise matinale impérative avec un verre d’eau.',
    contraindications: 'Infections évolutives, vaccins vivants atténués.',
    unitPrice: 42.0,
    presentation: 'Boîte de 20 comprimés sécables',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },

  // ==========================================
  // ANTIBIOTIQUES
  // ==========================================
  {
    id: 'mar_med_25',
    name: 'Clamoxyl 1 g',
    dci: 'Amoxicilline',
    dosage: '1000 mg',
    category: 'Antibiotique / Pénicilline',
    dosageForm: 'Comprimé dispersible',
    laboratory: 'GlaxoSmithKline (GSK) Maroc',
    defaultDosage: '1 comprimé matin et soir pendant 7 jours',
    defaultDuration: '7 jours',
    defaultInstructions: 'À dissoudre dans un verre d’eau ou à avaler entier au début ou au milieu des repas.',
    contraindications: 'Allergie confirmée aux pénicillines et bêta-lactamines, mononucléose infectieuse (MNI).',
    sideEffects: 'Diarrhée bénigne, nausées, rash cutané.',
    unitPrice: 51.5,
    presentation: 'Boîte de 14 comprimés dispersibles',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_26',
    name: 'Clamoxyl 500 mg',
    dci: 'Amoxicilline',
    dosage: '500 mg',
    category: 'Antibiotique / Pénicilline',
    dosageForm: 'Gélule',
    laboratory: 'GlaxoSmithKline (GSK) Maroc',
    defaultDosage: '1 gélule 3 fois par jour à intervalles réguliers',
    defaultDuration: '7 jours',
    defaultInstructions: 'Avaler avec un verre d’eau au cours des repas.',
    contraindications: 'Allergie aux bêta-lactamines.',
    unitPrice: 34.0,
    presentation: 'Boîte de 16 gélules',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_27',
    name: 'Clamoxyl Sirop 500 mg / 5 ml',
    dci: 'Amoxicilline',
    dosage: '500 mg / 5 ml',
    category: 'Antibiotique / Pénicilline',
    dosageForm: 'Poudre pour suspension buvable pédiatrique',
    laboratory: 'GlaxoSmithKline (GSK) Maroc',
    defaultDosage: '50 à 80 mg/kg/jour répartis en 2 ou 3 prises (selon cuillère-mesure)',
    defaultDuration: '7 à 10 jours',
    defaultInstructions: 'Reconstituer avec de l’eau minérale jusqu’au trait. Agiter avant chaque prise. Conserver au réfrigérateur après reconstitution.',
    contraindications: 'Allergie aux pénicillines.',
    unitPrice: 42.0,
    presentation: 'Flacon de 60 ml avec cuillère-mesure',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_28',
    name: 'Amoxil 1 g',
    dci: 'Amoxicilline',
    dosage: '1000 mg',
    category: 'Antibiotique / Pénicilline',
    dosageForm: 'Comprimé pelliculé',
    laboratory: 'Laprophan Maroc',
    defaultDosage: '1 comprimé 2 fois par jour à 12h d’intervalle',
    defaultDuration: '7 jours',
    defaultInstructions: 'Prendre au début des repas.',
    contraindications: 'Allergie aux bêta-lactamines.',
    unitPrice: 48.0,
    presentation: 'Boîte de 14 comprimés',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_29',
    name: 'Augmentin 1 g / 125 mg Adulte',
    dci: 'Amoxicilline + Acide clavulanique',
    dosage: '1000 mg / 125 mg',
    category: 'Antibiotique / Bêta-lactamine protégée',
    dosageForm: 'Poudre pour suspension en sachet / Comprimé',
    laboratory: 'GlaxoSmithKline (GSK) Maroc',
    defaultDosage: '1 sachet (ou comprimé) matin et soir au début des repas',
    defaultDuration: '7 à 10 jours',
    defaultInstructions: 'À prendre impérativement au début d’un repas pour minimiser les troubles digestifs.',
    contraindications: 'Allergie aux pénicillines, antécédent d’ictère ou hépatite sous amoxicilline/acide clavulanique.',
    sideEffects: 'Diarrhées, candidose cutanéo-muqueuse, nausées.',
    unitPrice: 79.5,
    presentation: 'Boîte de 14 sachets-doses (ou 16 comprimés)',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_30',
    name: 'Augmentin Nourrisson 100 mg / 12.5 mg',
    dci: 'Amoxicilline + Acide clavulanique',
    dosage: '100 mg / 12.5 mg / ml',
    category: 'Antibiotique / Bêta-lactamine protégée',
    dosageForm: 'Poudre pour suspension buvable pédiatrique',
    laboratory: 'GlaxoSmithKline (GSK) Maroc',
    defaultDosage: '80 mg/kg/jour en 3 prises réparties avec la pipette graduée en kg',
    defaultDuration: '7 à 10 jours',
    defaultInstructions: 'Bien agiter avant administration. Conserver au réfrigérateur après reconstitution max 7 jours.',
    contraindications: 'Allergie aux pénicillines, antécédent d’ictère.',
    unitPrice: 58.0,
    presentation: 'Flacon de 60 ml avec seringue pour administration orale',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_31',
    name: 'Curam 1 g / 125 mg',
    dci: 'Amoxicilline + Acide clavulanique',
    dosage: '1000 mg / 125 mg',
    category: 'Antibiotique / Bêta-lactamine protégée',
    dosageForm: 'Comprimé pelliculé',
    laboratory: 'Sandoz / Cooper Pharma Maroc',
    defaultDosage: '1 comprimé 2 fois par jour au début des repas',
    defaultDuration: '7 jours',
    defaultInstructions: 'Prendre avec un verre d’eau au début d’un repas.',
    contraindications: 'Allergie aux pénicillines, antécédent d’atteinte hépatique sous Curam.',
    unitPrice: 72.0,
    presentation: 'Boîte de 14 comprimés',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_32',
    name: 'Zithromax 500 mg',
    dci: 'Azithromycine',
    dosage: '500 mg',
    category: 'Antibiotique / Macrolide',
    dosageForm: 'Comprimé pelliculé',
    laboratory: 'Pfizer Maroc',
    defaultDosage: '1 comprimé par jour en 1 prise unique pendant 3 jours consécutifs',
    defaultDuration: '3 jours',
    defaultInstructions: 'Avaler avec un verre d’eau au milieu d’un repas.',
    contraindications: 'Allergie aux macrolides, insuffisance hépatique sévère, association avec dérivés de l’ergot de seigle.',
    sideEffects: 'Nausées, douleurs abdominales, allongement de l’intervalle QT.',
    unitPrice: 65.0,
    presentation: 'Boîte de 3 comprimés',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_33',
    name: 'Azix 500 mg',
    dci: 'Azithromycine',
    dosage: '500 mg',
    category: 'Antibiotique / Macrolide',
    dosageForm: 'Comprimé pelliculé',
    laboratory: 'Laprophan Maroc',
    defaultDosage: '1 comprimé par jour pendant 3 jours consécutifs',
    defaultDuration: '3 jours',
    defaultInstructions: 'Prendre au cours d’un repas à la même heure.',
    contraindications: 'Allergie aux macrolides, insuffisance hépatique.',
    unitPrice: 58.0,
    presentation: 'Boîte de 3 comprimés',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_34',
    name: 'Ciflox 500 mg',
    dci: 'Ciprofloxacine',
    dosage: '500 mg',
    category: 'Antibiotique / Fluoroquinolone',
    dosageForm: 'Comprimé pelliculé sécable',
    laboratory: 'Bayer / Pharma 5 Maroc',
    defaultDosage: '1 comprimé 2 fois par jour à 12h d’intervalle',
    defaultDuration: '5 à 10 jours',
    defaultInstructions: 'Boire abondamment pendant le traitement. Éviter l’exposition solaire intense (photosensibilisation).',
    contraindications: 'Antécédent de tendinopathie sous fluoroquinolones, enfant et adolescent en période de croissance, grossesse, allaitement.',
    sideEffects: 'Tendinite, risque de rupture tendineuse (tendon d’Achille), céphalées.',
    unitPrice: 68.5,
    presentation: 'Boîte de 10 comprimés',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_35',
    name: 'Flagyl 500 mg',
    dci: 'Métronidazole',
    dosage: '500 mg',
    category: 'Antibiotique / Antiparasitaire',
    dosageForm: 'Comprimé pelliculé',
    laboratory: 'Sanofi-Aventis Maroc',
    defaultDosage: '1 comprimé 2 à 3 fois par jour au cours des repas',
    defaultDuration: '7 à 10 jours',
    defaultInstructions: 'Prendre pendant les repas. Proscrire formellement toute consommation d’alcool (effet antabuse).',
    contraindications: 'Allergie aux imidazolés, premier trimestre de grossesse.',
    sideEffects: 'Goût métallique dans la bouche, nausées, urines foncées.',
    unitPrice: 24.5,
    presentation: 'Boîte de 20 comprimés',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_36',
    name: 'Oroken 200 mg',
    dci: 'Céfixime',
    dosage: '200 mg',
    category: 'Antibiotique / Céphalosporine 3G',
    dosageForm: 'Comprimé pelliculé',
    laboratory: 'Sanofi-Aventis Maroc',
    defaultDosage: '1 comprimé 2 fois par jour à 12 heures d’intervalle',
    defaultDuration: '5 à 8 jours',
    defaultInstructions: 'Avaler avec un verre d’eau au cours d’un repas.',
    contraindications: 'Allergie connue aux céphalosporines.',
    unitPrice: 84.0,
    presentation: 'Boîte de 8 comprimés',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_37',
    name: 'Bactrim Forte',
    dci: 'Sulfaméthoxazole + Triméthoprime',
    dosage: '800 mg / 160 mg',
    category: 'Antibiotique / Sulfamide',
    dosageForm: 'Comprimé sécable',
    laboratory: 'Roche / Maphar Maroc',
    defaultDosage: '1 comprimé matin et soir au milieu des repas',
    defaultDuration: '5 à 10 jours',
    defaultInstructions: 'Boire au moins 1.5 litre d’eau par jour pour prévenir la cristallurie.',
    contraindications: 'Allergie aux sulfamides, déficit en G6PD, insuffisance hépatique ou rénale sévère.',
    unitPrice: 38.0,
    presentation: 'Boîte de 10 comprimés',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_38',
    name: 'Pyostacine 500 mg',
    dci: 'Pristinamycine',
    dosage: '500 mg',
    category: 'Antibiotique / Synergistine',
    dosageForm: 'Comprimé pelliculé',
    laboratory: 'Sanofi-Aventis Maroc',
    defaultDosage: '2 comprimés 2 à 3 fois par jour au milieu des repas',
    defaultDuration: '7 à 10 jours',
    defaultInstructions: 'Prendre avec un verre d’eau au milieu des repas.',
    contraindications: 'Allergie à la pristinamycine, allaitement.',
    unitPrice: 96.0,
    presentation: 'Boîte de 16 comprimés',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_39',
    name: 'Vibramycine 100 mg (Doxycycline)',
    dci: 'Doxycycline monohydratée',
    dosage: '100 mg',
    category: 'Antibiotique / Tétracycline',
    dosageForm: 'Comprimé sécable',
    laboratory: 'Pfizer Maroc',
    defaultDosage: '1 comprimé par jour au milieu d’un grand repas',
    defaultDuration: '10 à 28 jours (acné/infection)',
    defaultInstructions: 'Prendre assis ou debout avec un grand verre d’eau au milieu du repas. Ne pas s’allonger dans les 30 minutes (risque d’ulcération œsophagienne). Éviter le soleil.',
    contraindications: 'Enfant de moins de 8 ans (coloration des dents), grossesse, allaitement.',
    unitPrice: 32.5,
    presentation: 'Boîte de 10 comprimés',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },

  // ==========================================
  // GASTRO-ENTÉROLOGIE & ANTISPASMODIQUES
  // ==========================================
  {
    id: 'mar_med_40',
    name: 'Spasfon 80 mg',
    dci: 'Phloroglucinol',
    dosage: '80 mg',
    category: 'Antispasmodique musculotrope',
    dosageForm: 'Comprimé enrobé',
    laboratory: 'Teva / Cooper Pharma Maroc',
    defaultDosage: '2 comprimés au moment des crises spasmodiques (max 6 comprimés/jour)',
    defaultDuration: '3 à 5 jours',
    defaultInstructions: 'À avaler avec un verre d’eau.',
    contraindications: 'Allergie connue aux composants.',
    sideEffects: 'Rares éruptions cutanées d’origine allergique.',
    unitPrice: 22.0,
    presentation: 'Boîte de 30 comprimés',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_41',
    name: 'Spasfon Lyoc 80 mg',
    dci: 'Phloroglucinol',
    dosage: '80 mg Lyoc',
    category: 'Antispasmodique musculotrope',
    dosageForm: 'Lyophilisat oral',
    laboratory: 'Teva / Cooper Pharma Maroc',
    defaultDosage: '2 lyophilisats au moment de la crise, à renouveler si persistance',
    defaultDuration: '3 à 5 jours',
    defaultInstructions: 'Laisser fondre sous la langue ou dissoudre dans un demi-verre d’eau pour une action rapide.',
    contraindications: 'Allergie au phloroglucinol.',
    unitPrice: 26.5,
    presentation: 'Boîte de 10 lyophilisats oraux',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_42',
    name: 'Debridat 100 mg',
    dci: 'Trimébutine',
    dosage: '100 mg',
    category: 'Régulateur de la motricité digestive',
    dosageForm: 'Comprimé pelliculé',
    laboratory: 'Pfizer / Viatris Maroc',
    defaultDosage: '1 comprimé 3 fois par jour avant les repas',
    defaultDuration: '7 à 14 jours',
    defaultInstructions: 'Prendre 15 à 30 minutes avant les repas principaux.',
    contraindications: 'Hypersensibilité à la trimébutine.',
    unitPrice: 34.2,
    presentation: 'Boîte de 30 comprimés',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_43',
    name: 'Meteospasmyl',
    dci: 'Alvérine + Siméticone',
    dosage: '60 mg / 300 mg',
    category: 'Antispasmodique & Antiflatulent',
    dosageForm: 'Capsule molle',
    laboratory: 'Mayoly Spindler / Galenica Maroc',
    defaultDosage: '1 capsule 2 à 3 fois par jour au début des repas',
    defaultDuration: '10 à 15 jours',
    defaultInstructions: 'Avaler avec un verre d’eau au début du repas.',
    contraindications: 'Allergie à l’alvérine ou aux excipients.',
    unitPrice: 42.0,
    presentation: 'Boîte de 30 capsules molles',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_44',
    name: 'Mopral 20 mg (Oméprazole)',
    dci: 'Oméprazole',
    dosage: '20 mg',
    category: 'Inhibiteur de la pompe à protons (IPP)',
    dosageForm: 'Gélule gastro-résistante',
    laboratory: 'AstraZeneca / Laprophan Maroc',
    defaultDosage: '1 gélule le matin à jeun 30 minutes avant le petit-déjeuner',
    defaultDuration: '14 à 28 jours',
    defaultInstructions: 'Avaler la gélule entière avec un verre d’eau sans l’ouvrir ni la croquer.',
    contraindications: 'Association avec le nelfinavir, allergie aux dérivés benzimidazolés.',
    sideEffects: 'Céphalées légères, diarrhée ou constipation passagère.',
    unitPrice: 62.0,
    presentation: 'Boîte de 14 gélules',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_45',
    name: 'Inexium 20 mg',
    dci: 'Esoméprazole',
    dosage: '20 mg',
    category: 'Inhibiteur de la pompe à protons (IPP)',
    dosageForm: 'Comprimé gastro-résistant',
    laboratory: 'AstraZeneca Maroc',
    defaultDosage: '1 comprimé par jour le matin à jeun',
    defaultDuration: '14 à 28 jours',
    defaultInstructions: 'Prendre avec un verre d’eau le matin. Ne pas mâcher.',
    contraindications: 'Association au nelfinavir.',
    unitPrice: 68.0,
    presentation: 'Boîte de 14 comprimés',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_46',
    name: 'Inexium 40 mg',
    dci: 'Esoméprazole',
    dosage: '40 mg',
    category: 'Inhibiteur de la pompe à protons (IPP)',
    dosageForm: 'Comprimé gastro-résistant',
    laboratory: 'AstraZeneca Maroc',
    defaultDosage: '1 comprimé par jour le matin à jeun (reflux sévère / éradication H. pylori)',
    defaultDuration: '28 jours',
    defaultInstructions: 'Avaler entier 30 minutes avant le repas du matin.',
    contraindications: 'Hypersensibilité aux IPP.',
    unitPrice: 98.0,
    presentation: 'Boîte de 14 comprimés',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_47',
    name: 'Pariet 20 mg',
    dci: 'Rabéprazole sodique',
    dosage: '20 mg',
    category: 'Inhibiteur de la pompe à protons (IPP)',
    dosageForm: 'Comprimé gastro-résistant',
    laboratory: 'Janssen-Cilag / Maphar Maroc',
    defaultDosage: '1 comprimé le matin à jeun',
    defaultDuration: '14 à 28 jours',
    defaultInstructions: 'Avaler le comprimé entier.',
    contraindications: 'Allergie aux IPP, grossesse.',
    unitPrice: 76.5,
    presentation: 'Boîte de 14 comprimés',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_48',
    name: 'Gaviscon Suspension Buvable Sachets',
    dci: 'Alginate de sodium + Bicarbonate de sodium',
    dosage: '500 mg / 267 mg par sachet',
    category: 'Anti-reflux gastro-œsophagien',
    dosageForm: 'Suspension buvable en sachet',
    laboratory: 'Reckitt Benckiser / Cooper Pharma Maroc',
    defaultDosage: '1 sachet après les 3 repas principaux et éventuellement au coucher',
    defaultDuration: '7 à 14 jours',
    defaultInstructions: 'Bien malaxer le sachet avant ouverture. Prendre 20 minutes après les repas et au coucher sans boire immédiatement après.',
    contraindications: 'Régime sans sel très strict (contient du sodium).',
    unitPrice: 32.0,
    presentation: 'Boîte de 24 sachets de 10 ml',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_49',
    name: 'Motilium 10 mg',
    dci: 'Dompéridone',
    dosage: '10 mg',
    category: 'Antiémétique / Modificateur motricité gastrique',
    dosageForm: 'Comprimé pelliculé',
    laboratory: 'Janssen-Cilag / Maphar Maroc',
    defaultDosage: '1 comprimé 3 fois par jour 15 à 30 minutes avant les repas (max 30mg/jour)',
    defaultDuration: '3 à 7 jours (durée la plus courte possible)',
    defaultInstructions: 'Prendre avant les repas. Ne pas dépasser la posologie recommandée.',
    contraindications: 'Allongement de l’intervalle QTc, hémorragie digestive, obstruction mécanique intestinale.',
    unitPrice: 28.5,
    presentation: 'Boîte de 30 comprimés',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_50',
    name: 'Smecta Sachets',
    dci: 'Diosmectite',
    dosage: '3 g',
    category: 'Antidiarrhéique / Pansement digestif',
    dosageForm: 'Poudre pour suspension buvable en sachet',
    laboratory: 'Ipsen Pharma / Maphar Maroc',
    defaultDosage: '1 sachet 3 fois par jour délayé dans un demi-verre d’eau',
    defaultDuration: '3 à 5 jours',
    defaultInstructions: 'À prendre à distance des autres médicaments (au moins 2 heures d’intervalle). Bien hydrater le patient.',
    contraindications: 'Obstruction intestinale.',
    unitPrice: 26.0,
    presentation: 'Boîte de 30 sachets',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_51',
    name: 'Imodium 2 mg',
    dci: 'Lopéramide',
    dosage: '2 mg',
    category: 'Antidiarrhéique ralentisseur du transit',
    dosageForm: 'Gélule',
    laboratory: 'Janssen-Cilag / Johnson & Johnson Maroc',
    defaultDosage: '2 gélules d’emblée, puis 1 gélule après chaque selle liquide non moulée (max 6 gélules/jour)',
    defaultDuration: '2 à 3 jours',
    defaultInstructions: 'Arrêter le traitement dès normalisation des selles. Boire abondamment.',
    contraindications: 'Diarrhée sanglante avec fièvre élevée (syndrome dysentérique), colite ulcéreuse aiguë, enfant < 8 ans.',
    unitPrice: 19.5,
    presentation: 'Boîte de 20 gélules',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_52',
    name: 'Duspatalin 200 mg',
    dci: 'Mébévérine',
    dosage: '200 mg Retard',
    category: 'Antispasmodique colique',
    dosageForm: 'Gélule à libération prolongée',
    laboratory: 'Abbott / Mylan Maroc',
    defaultDosage: '1 gélule matin et soir 20 minutes avant les repas',
    defaultDuration: '15 à 30 jours',
    defaultInstructions: 'Avaler avec un verre d’eau sans croquer.',
    contraindications: 'Allergie à la mébévérine.',
    unitPrice: 52.0,
    presentation: 'Boîte de 30 gélules retard',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },

  // ==========================================
  // PNEUMOLOGIE, ORL & ALLERGOLOGIE
  // ==========================================
  {
    id: 'mar_med_53',
    name: 'Ventoline Aérosol 100 µg',
    dci: 'Salbutamol',
    dosage: '100 µg par bouffée',
    category: 'Bronchodilatateur d’action rapide / Bêta-2 mimétique',
    dosageForm: 'Suspension pour inhalation en flacon pressurisé',
    laboratory: 'GlaxoSmithKline (GSK) Maroc',
    defaultDosage: '1 à 2 bouffées au moment des crises de dyspnée (à renouveler après quelques minutes si besoin)',
    defaultDuration: 'Traitement de secours à la demande',
    defaultInstructions: 'Bien agiter le flacon, expirer profondément, déclencher la bouffée au début d’une inspiration lente et profonde, retenir la respiration 10 secondes.',
    contraindications: 'Intolérance au salbutamol.',
    sideEffects: 'Tremblements des extrémités, tachycardie passagère.',
    unitPrice: 32.5,
    presentation: 'Flacon pressurisé de 200 bouffées avec embout buccal',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_54',
    name: 'Seretide Diskus 50 / 250 µg',
    dci: 'Salmétérol + Fluticasone propionate',
    dosage: '50 µg / 250 µg',
    category: 'Traitement de fond de l’asthme et BPCO',
    dosageForm: 'Poudre pour inhalation en récipient unidose',
    laboratory: 'GlaxoSmithKline (GSK) Maroc',
    defaultDosage: '1 inhalation matin et soir à 12 heures d’intervalle',
    defaultDuration: 'Traitement au long cours',
    defaultInstructions: 'Rincer impérativement la bouche à l’eau après chaque inhalation pour éviter la candidose buccale.',
    contraindications: 'Tuberculose pulmonaire évolutive, allergie aux protéines du lait.',
    unitPrice: 220.0,
    presentation: 'Inhalateur Diskus de 60 doses',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_55',
    name: 'Symbicort Turbuhaler 160 / 4.5 µg',
    dci: 'Budésonide + Formotérol',
    dosage: '160 µg / 4.5 µg',
    category: 'Traitement de fond et secours asthme',
    dosageForm: 'Poudre pour inhalation',
    laboratory: 'AstraZeneca Maroc',
    defaultDosage: '1 à 2 inhalations matin et soir',
    defaultDuration: 'Traitement continu',
    defaultInstructions: 'Inspiration forte et profonde. Rincer la bouche après prise.',
    contraindications: 'Hypersensibilité aux principes actifs.',
    unitPrice: 215.0,
    presentation: 'Inhalateur Turbuhaler de 120 doses',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_56',
    name: 'Aerius 5 mg',
    dci: 'Desloratadine',
    dosage: '5 mg',
    category: 'Antihistaminique H1 non sédatif',
    dosageForm: 'Comprimé pelliculé',
    laboratory: 'Organon / MSD Maroc',
    defaultDosage: '1 comprimé par jour au coucher ou le matin',
    defaultDuration: '7 à 30 jours',
    defaultInstructions: 'À avaler avec de l’eau au cours ou en dehors des repas.',
    contraindications: 'Hypersensibilité à la desloratadine ou à la loratadine.',
    unitPrice: 44.5,
    presentation: 'Boîte de 15 comprimés',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_57',
    name: 'Aerius Sirop 0.5 mg/ml',
    dci: 'Desloratadine',
    dosage: '0.5 mg / ml',
    category: 'Antihistaminique H1 pédiatrique',
    dosageForm: 'Sirop',
    laboratory: 'Organon / MSD Maroc',
    defaultDosage: '2.5 ml par jour (enfant 1-5 ans) ou 5 ml par jour (enfant 6-11 ans)',
    defaultDuration: '7 à 14 jours',
    defaultInstructions: 'Utiliser la seringue graduée pour administration orale.',
    contraindications: 'Allergie à la desloratadine.',
    unitPrice: 38.0,
    presentation: 'Flacon de 60 ml avec seringue doseuse',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_58',
    name: 'Zyrtec 10 mg',
    dci: 'Cétirizine',
    dosage: '10 mg',
    category: 'Antihistaminique H1',
    dosageForm: 'Comprimé pelliculé sécable',
    laboratory: 'UCB Pharma / Sothema Maroc',
    defaultDosage: '1 comprimé par jour le soir au coucher',
    defaultDuration: '7 à 20 jours',
    defaultInstructions: 'Prendre avec un verre d’eau.',
    contraindications: 'Insuffisance rénale terminale (clairance < 10 ml/min).',
    unitPrice: 36.0,
    presentation: 'Boîte de 20 comprimés',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_59',
    name: 'Xyzall 5 mg',
    dci: 'Lévocétirizine',
    dosage: '5 mg',
    category: 'Antihistaminique H1',
    dosageForm: 'Comprimé pelliculé',
    laboratory: 'UCB Pharma / Sothema Maroc',
    defaultDosage: '1 comprimé par jour le soir',
    defaultDuration: '10 à 28 jours',
    defaultInstructions: 'Avaler avec un verre d’eau.',
    contraindications: 'Insuffisance rénale sévère.',
    unitPrice: 42.0,
    presentation: 'Boîte de 14 comprimés',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_60',
    name: 'Toplexil Sirop',
    dci: 'Oxomémazine',
    dosage: '0.33 mg / ml',
    category: 'Antitussif antihistaminique',
    dosageForm: 'Sirop',
    laboratory: 'Sanofi-Aventis Maroc',
    defaultDosage: '10 ml 2 à 4 fois par jour en privilégiant les prises vespérales',
    defaultDuration: '3 à 5 jours',
    defaultInstructions: 'Attention à la somnolence diurne. Ne pas conduire de véhicules.',
    contraindications: 'Toux productive grasse (respecter l’expectoration), antécédent d’agranulocytose, risque de glaucome par fermeture de l’angle.',
    unitPrice: 16.5,
    presentation: 'Flacon de 150 ml avec gobelet doseur',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_61',
    name: 'Rhinathiol 2% Enfant',
    dci: 'Carbocistéine',
    dosage: '2%',
    category: 'Mucofluidifiant bronchique',
    dosageForm: 'Sirop',
    laboratory: 'Sanofi-Aventis Maroc',
    defaultDosage: '1 cuillère-mesure de 5 ml 2 à 3 fois par jour',
    defaultDuration: '5 jours',
    defaultInstructions: 'Ne pas administrer avant le coucher. Hydrater abondamment.',
    contraindications: 'Nourrisson de moins de 2 ans (risque d’encombrement bronchique), ulcère gastrique.',
    unitPrice: 15.0,
    presentation: 'Flacon de 125 ml avec cuillère-mesure',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_62',
    name: 'Rhinathiol 5% Adulte',
    dci: 'Carbocistéine',
    dosage: '5%',
    category: 'Mucofluidifiant bronchique',
    dosageForm: 'Sirop',
    laboratory: 'Sanofi-Aventis Maroc',
    defaultDosage: '1 cuillère à soupe (15 ml) 3 fois par jour à distance du coucher',
    defaultDuration: '5 à 8 jours',
    defaultInstructions: 'Facilite l’expectoration des sécrétions bronchiques.',
    contraindications: 'Ulcère gastro-duodénal actif.',
    unitPrice: 22.0,
    presentation: 'Flacon de 200 ml',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_63',
    name: 'Solmucol 200 mg',
    dci: 'Acétylcystéine',
    dosage: '200 mg',
    category: 'Fluidifiant bronchique / Mucolytique',
    dosageForm: 'Granulés pour solution buvable en sachet',
    laboratory: 'IBSA / Laprophan Maroc',
    defaultDosage: '1 sachet dissous dans de l’eau 3 fois par jour',
    defaultDuration: '5 à 7 jours',
    defaultInstructions: 'Prendre de préférence après les repas dans un demi-verre d’eau.',
    contraindications: 'Ulcère gastrique, enfant < 2 ans.',
    unitPrice: 24.0,
    presentation: 'Boîte de 20 sachets',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_64',
    name: 'Pivalone 1% Spray Nasal',
    dci: 'Tixocortol pivalate',
    dosage: '1%',
    category: 'Corticoïde local / Rhinite & Sinusite',
    dosageForm: 'Suspension pour pulvérisation nasale',
    laboratory: 'Pfizer Maroc',
    defaultDosage: '1 à 2 pulvérisations dans chaque narine 3 à 4 fois par jour',
    defaultDuration: '5 à 7 jours',
    defaultInstructions: 'Se moucher soigneusement avant chaque pulvérisation. Agiter vigoureusement le flacon.',
    contraindications: 'Épistaxis récent, lésions nasales virales ou mycosiques.',
    unitPrice: 24.5,
    presentation: 'Flacon pulvérisateur de 10 ml',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_65',
    name: 'Rhinafathiol Spray Nasal',
    dci: 'Tuaminoheptane + Benzalkonium',
    dosage: 'Association décongestionnante',
    category: 'Décongestionnant nasal',
    dosageForm: 'Solution nasale pour pulvérisation',
    laboratory: 'Sanofi-Aventis Maroc',
    defaultDosage: '1 pulvérisation dans chaque narine 2 à 3 fois par jour (max 5 jours)',
    defaultDuration: '3 à 5 jours max',
    defaultInstructions: 'Usage temporaire strict pour éviter la rhinite médicamenteuse.',
    contraindications: 'Enfant < 15 ans, hypertension artérielle sévère, antécédent d’AVC, glaucome à angle fermé.',
    unitPrice: 18.0,
    presentation: 'Flacon pulvérisateur de 15 ml',
    reimbursementRate: 'Non remboursable',
    isPreloaded: true,
    isActive: true,
  },

  // ==========================================
  // CARDIOLOGIE, HYPERTENSION & LIPIDES
  // ==========================================
  {
    id: 'mar_med_66',
    name: 'Coversyl 5 mg',
    dci: 'Périndopril arginine',
    dosage: '5 mg',
    category: 'Antihypertenseur / IEC',
    dosageForm: 'Comprimé pelliculé sécable',
    laboratory: 'Servier Maroc',
    defaultDosage: '1 comprimé par jour le matin en 1 prise avant le petit-déjeuner',
    defaultDuration: 'Traitement chronique',
    defaultInstructions: 'Prendre le matin avant le repas. Surveiller la fonction rénale et la kaliémie.',
    contraindications: 'Antécédent d’angio-œdème (œdème de Quincke) sous IEC, grossesse (2ème et 3ème trimestres).',
    sideEffects: 'Toux sèche nocturne irritative, hypotension orthostatique, hyperkaliémie.',
    unitPrice: 78.5,
    presentation: 'Boîte de 30 comprimés',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_67',
    name: 'Coversyl 10 mg',
    dci: 'Périndopril arginine',
    dosage: '10 mg',
    category: 'Antihypertenseur / IEC',
    dosageForm: 'Comprimé pelliculé',
    laboratory: 'Servier Maroc',
    defaultDosage: '1 comprimé le matin en 1 prise',
    defaultDuration: 'Traitement chronique',
    defaultInstructions: 'Prise matinale régulière.',
    contraindications: 'Angio-œdème héréditaire ou sous IEC, grossesse.',
    unitPrice: 115.0,
    presentation: 'Boîte de 30 comprimés',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_68',
    name: 'Amlor 5 mg',
    dci: 'Amlodipine bésylate',
    dosage: '5 mg',
    category: 'Antihypertenseur / Inhibiteur calcique',
    dosageForm: 'Gélule',
    laboratory: 'Pfizer Maroc',
    defaultDosage: '1 gélule par jour le matin',
    defaultDuration: 'Traitement chronique au long cours',
    defaultInstructions: 'À prendre chaque jour à la même heure.',
    contraindications: 'Hypotension sévère, choc cardiogénique, rétrécissement aortique serré.',
    sideEffects: 'Œdèmes malléolaires bilatéraux des membres inférieurs, bouffées vasomotrices.',
    unitPrice: 74.0,
    presentation: 'Boîte de 30 gélules',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_69',
    name: 'Amlor 10 mg',
    dci: 'Amlodipine bésylate',
    dosage: '10 mg',
    category: 'Antihypertenseur / Inhibiteur calcique',
    dosageForm: 'Gélule',
    laboratory: 'Pfizer Maroc',
    defaultDosage: '1 gélule par jour le matin',
    defaultDuration: 'Traitement chronique',
    defaultInstructions: 'Prise orale le matin.',
    contraindications: 'Choc cardiogénique, hypotension sévère.',
    unitPrice: 110.0,
    presentation: 'Boîte de 30 gélules',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_70',
    name: 'Co-Tareg 80 / 12.5 mg',
    dci: 'Valsartan + Hydrochlorothiazide',
    dosage: '80 mg / 12.5 mg',
    category: 'Antihypertenseur / ARA II + Diurétique',
    dosageForm: 'Comprimé pelliculé',
    laboratory: 'Novartis Pharma Maroc',
    defaultDosage: '1 comprimé par jour le matin au petit-déjeuner',
    defaultDuration: 'Traitement chronique',
    defaultInstructions: 'Prise régulière le matin. Contrôler régulièrement l’ionogramme sanguin (Na, K) et la créatinine.',
    contraindications: 'Insuffisance hépatique ou rénale sévère, grossesse T2 et T3, hypokaliémie réfractaire.',
    unitPrice: 108.0,
    presentation: 'Boîte de 28 comprimés pelliculés',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_71',
    name: 'Co-Tareg 160 / 12.5 mg',
    dci: 'Valsartan + Hydrochlorothiazide',
    dosage: '160 mg / 12.5 mg',
    category: 'Antihypertenseur / ARA II + Diurétique',
    dosageForm: 'Comprimé pelliculé',
    laboratory: 'Novartis Pharma Maroc',
    defaultDosage: '1 comprimé le matin en 1 prise quotidienne',
    defaultDuration: 'Traitement chronique',
    defaultInstructions: 'Prendre le matin avec un verre d’eau.',
    contraindications: 'Grossesse, insuffisance rénale sévère, anurie.',
    unitPrice: 125.0,
    presentation: 'Boîte de 28 comprimés',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_72',
    name: 'Tareg 80 mg',
    dci: 'Valsartan',
    dosage: '80 mg',
    category: 'Antihypertenseur / ARA II (Sartan)',
    dosageForm: 'Comprimé pelliculé sécable',
    laboratory: 'Novartis Pharma Maroc',
    defaultDosage: '1 comprimé par jour le matin',
    defaultDuration: 'Traitement continu',
    defaultInstructions: 'Prise quotidienne régulière.',
    contraindications: 'Grossesse, cirrhose biliaire cholestatique.',
    unitPrice: 84.0,
    presentation: 'Boîte de 28 comprimés',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_73',
    name: 'Aprovel 150 mg',
    dci: 'Irbésartan',
    dosage: '150 mg',
    category: 'Antihypertenseur / ARA II',
    dosageForm: 'Comprimé pelliculé',
    laboratory: 'Sanofi-Aventis Maroc',
    defaultDosage: '1 comprimé par jour le matin avec ou sans aliment',
    defaultDuration: 'Traitement au long cours',
    defaultInstructions: 'Surveillance tensionnelle et de la créatininémie.',
    contraindications: 'Grossesse (trimestres 2 et 3).',
    unitPrice: 82.0,
    presentation: 'Boîte de 28 comprimés',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_74',
    name: 'CoAprovel 150 / 12.5 mg',
    dci: 'Irbésartan + Hydrochlorothiazide',
    dosage: '150 mg / 12.5 mg',
    category: 'Antihypertenseur / Association ARA II + Diurétique',
    dosageForm: 'Comprimé pelliculé',
    laboratory: 'Sanofi-Aventis Maroc',
    defaultDosage: '1 comprimé le matin en 1 prise quotidienne',
    defaultDuration: 'Traitement chronique',
    defaultInstructions: 'Prise matinale.',
    contraindications: 'Grossesse, insuffisance rénale sévère.',
    unitPrice: 104.0,
    presentation: 'Boîte de 28 comprimés',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_75',
    name: 'Lasilix 40 mg (Furosémide)',
    dci: 'Furosémide',
    dosage: '40 mg',
    category: 'Diurétique de l’anse',
    dosageForm: 'Comprimé sécable',
    laboratory: 'Sanofi-Aventis Maroc',
    defaultDosage: '1 comprimé par jour le matin (adapter selon la réponse diurétique)',
    defaultDuration: 'Selon indication (insuffisance cardiaque / HTA / rétention)',
    defaultInstructions: 'À prendre impérativement le matin pour éviter les réveils nocturnes. Surveiller ionogramme (kaliémie).',
    contraindications: 'Insuffisance rénale anurique, déshydratation aiguë, hypokaliémie sévère.',
    unitPrice: 24.5,
    presentation: 'Boîte de 30 comprimés sécables',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_76',
    name: 'Tenormine 100 mg (Aténolol)',
    dci: 'Aténolol',
    dosage: '100 mg',
    category: 'Bêta-bloquant cardiosélectif',
    dosageForm: 'Comprimé sécable',
    laboratory: 'AstraZeneca / Laprophan Maroc',
    defaultDosage: '1/2 à 1 comprimé par jour le matin',
    defaultDuration: 'Traitement continu',
    defaultInstructions: 'Ne jamais interrompre brutalement le traitement. Mesurer pouls et tension.',
    contraindications: 'Asthme et BPCO sévère, bradycardie < 50 bpm, BAV 2 et 3, insuffisance cardiaque décompensée.',
    unitPrice: 42.0,
    presentation: 'Boîte de 28 comprimés',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_77',
    name: 'Cardensiel 2.5 mg',
    dci: 'Bisoprolol fumarate',
    dosage: '2.5 mg',
    category: 'Bêta-bloquant',
    dosageForm: 'Comprimé pelliculé sécable',
    laboratory: 'Merck Serono / Cooper Pharma Maroc',
    defaultDosage: '1 comprimé par jour le matin',
    defaultDuration: 'Traitement au long cours',
    defaultInstructions: 'Prise le matin.',
    contraindications: 'Insuffisance cardiaque aiguë, bradycardie sévère.',
    unitPrice: 38.0,
    presentation: 'Boîte de 30 comprimés',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_78',
    name: 'Nebilox 5 mg',
    dci: 'Nébivolol',
    dosage: '5 mg',
    category: 'Bêta-bloquant vasodilatateur',
    dosageForm: 'Comprimé quadrisécable',
    laboratory: 'Menarini / Maphar Maroc',
    defaultDosage: '1 comprimé par jour de préférence au même moment',
    defaultDuration: 'Traitement chronique',
    defaultInstructions: 'Prendre avec un verre d’eau.',
    contraindications: 'Insuffisance hépatique sévère, bradycardie sinusale.',
    unitPrice: 62.0,
    presentation: 'Boîte de 28 comprimés',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_79',
    name: 'Kardegic 75 mg',
    dci: 'Acétylsalicylate de lysine',
    dosage: '75 mg',
    category: 'Antiagrégant plaquettaire',
    dosageForm: 'Poudre pour solution buvable en sachet',
    laboratory: 'Sanofi-Aventis Maroc',
    defaultDosage: '1 sachet par jour au milieu du déjeuner ou du dîner',
    defaultDuration: 'Traitement préventif cardiovasculaire au long cours',
    defaultInstructions: 'Dissoudre dans un verre d’eau au cours d’un repas.',
    contraindications: 'Allergie aux salicylés, maladie ulcéreuse active, syndrome hémorragique.',
    unitPrice: 18.0,
    presentation: 'Boîte de 30 sachets-doses',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_80',
    name: 'Kardegic 160 mg',
    dci: 'Acétylsalicylate de lysine',
    dosage: '160 mg',
    category: 'Antiagrégant plaquettaire',
    dosageForm: 'Poudre pour solution buvable en sachet',
    laboratory: 'Sanofi-Aventis Maroc',
    defaultDosage: '1 sachet par jour au milieu d’un repas',
    defaultDuration: 'Traitement continu',
    defaultInstructions: 'Prendre au milieu d’un repas après dissolution dans de l’eau.',
    contraindications: 'Risque hémorragique avéré, ulcère en évolution.',
    unitPrice: 21.0,
    presentation: 'Boîte de 30 sachets-doses',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_81',
    name: 'Sintrom 4 mg',
    dci: 'Acénocoumarol',
    dosage: '4 mg',
    category: 'Anticoagulant oral / Antivitamine K (AVK)',
    dosageForm: 'Comprimé quadrisécable en croix',
    laboratory: 'Novartis Pharma Maroc',
    defaultDosage: 'Dose quotidienne ajustée selon l’INR en prise unique le soir vers 18h',
    defaultDuration: 'Traitement chronique sous contrôle régulier de l’INR',
    defaultInstructions: 'Prendre chaque jour à heure fixe le soir. Contrôle INR obligatoire. Fournir le carnet de suivi AVK au patient.',
    contraindications: 'Lésions organiques susceptibles de saigner, insuffisance hépatique ou rénale sévère, grossesse.',
    sideEffects: 'Hémorragies majeures ou mineures (gingivorragies, épistaxis, hématomes).',
    unitPrice: 16.5,
    presentation: 'Boîte de 20 comprimés quadrisécables',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_82',
    name: 'Xarelto 20 mg',
    dci: 'Rivaroxaban',
    dosage: '20 mg',
    category: 'Anticoagulant oral direct (AOD) / Inhibiteur Xa',
    dosageForm: 'Comprimé pelliculé',
    laboratory: 'Bayer Maroc',
    defaultDosage: '1 comprimé par jour au milieu d’un repas à heure fixe',
    defaultDuration: 'Traitement au long cours selon indication (FA / TVP)',
    defaultInstructions: 'Doit impérativement être pris au cours d’un repas pour assurer une absorption optimale.',
    contraindications: 'Saignement évolutif cliniquement significatif, atteinte hépatique associée à une coagulopathie.',
    unitPrice: 420.0,
    presentation: 'Boîte de 28 comprimés pelliculés',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_83',
    name: 'Eliquis 5 mg',
    dci: 'Apixaban',
    dosage: '5 mg',
    category: 'Anticoagulant oral direct (AOD)',
    dosageForm: 'Comprimé pelliculé',
    laboratory: 'Bristol-Myers Squibb / Pfizer Maroc',
    defaultDosage: '1 comprimé 2 fois par jour à 12h d’intervalle avec ou sans aliment',
    defaultDuration: 'Traitement continu',
    defaultInstructions: 'Prendre matin et soir à heure régulière.',
    contraindications: 'Saignement actif, insuffisance rénale terminale.',
    unitPrice: 390.0,
    presentation: 'Boîte de 56 comprimés',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_84',
    name: 'Tahor 20 mg (Atorvastatine)',
    dci: 'Atorvastatine calcique',
    dosage: '20 mg',
    category: 'Hypolipémiant / Statine',
    dosageForm: 'Comprimé pelliculé',
    laboratory: 'Pfizer Maroc',
    defaultDosage: '1 comprimé par jour le soir au coucher',
    defaultDuration: 'Traitement continu au long cours',
    defaultInstructions: 'Prise de préférence le soir. Signaler immédiatement toute douleur musculaire inexpliquée (myalgie).',
    contraindications: 'Affection hépatique évolutive, élévation prolongée inexpliquée des transaminases, myopathie active, grossesse.',
    sideEffects: 'Myalgies, crampes musculaires, élévation modérée des CPK et transaminases.',
    unitPrice: 110.0,
    presentation: 'Boîte de 30 comprimés',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_85',
    name: 'Tahor 40 mg',
    dci: 'Atorvastatine calcique',
    dosage: '40 mg',
    category: 'Hypolipémiant / Statine',
    dosageForm: 'Comprimé pelliculé',
    laboratory: 'Pfizer Maroc',
    defaultDosage: '1 comprimé le soir au coucher',
    defaultDuration: 'Traitement chronique',
    defaultInstructions: 'Prendre le soir avec un verre d’eau.',
    contraindications: 'Maladie hépatique active, grossesse.',
    unitPrice: 165.0,
    presentation: 'Boîte de 30 comprimés',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_86',
    name: 'Crestor 10 mg',
    dci: 'Rosuvastatine',
    dosage: '10 mg',
    category: 'Hypolipémiant / Statine',
    dosageForm: 'Comprimé pelliculé',
    laboratory: 'AstraZeneca Maroc',
    defaultDosage: '1 comprimé par jour à n’importe quel moment de la journée',
    defaultDuration: 'Traitement chronique',
    defaultInstructions: 'Prise quotidienne avec ou sans aliment.',
    contraindications: 'Hépatopathie active, insuffisance rénale sévère, myopathie.',
    unitPrice: 125.0,
    presentation: 'Boîte de 28 comprimés',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },

  // ==========================================
  // DIABÉTOLOGIE & ENDOCRINOLOGIE
  // ==========================================
  {
    id: 'mar_med_87',
    name: 'Glucophage 850 mg',
    dci: 'Metformine chlorhydrate',
    dosage: '850 mg',
    category: 'Antidiabétique oral / Biguanide',
    dosageForm: 'Comprimé pelliculé',
    laboratory: 'Merck Serono / Cooper Pharma Maroc',
    defaultDosage: '1 comprimé 2 fois par jour au milieu ou à la fin des repas (déjeuner et dîner)',
    defaultDuration: 'Traitement chronique du diabète de type 2',
    defaultInstructions: 'Prendre impérativement au milieu ou en fin de repas pour limiter les troubles digestifs. Interrompre 48h avant tout scanner injecté.',
    contraindications: 'Insuffisance rénale modérée à sévère (DFG < 30 ml/min), acidose métabolique, état d’hypoxie tissulaire.',
    sideEffects: 'Troubles digestifs en début de traitement (diarrhée, nausées, météorisme), goût métallique.',
    unitPrice: 38.0,
    presentation: 'Boîte de 30 comprimés',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_88',
    name: 'Glucophage 1000 mg',
    dci: 'Metformine chlorhydrate',
    dosage: '1000 mg',
    category: 'Antidiabétique oral / Biguanide',
    dosageForm: 'Comprimé pelliculé sécable',
    laboratory: 'Merck Serono / Cooper Pharma Maroc',
    defaultDosage: '1 comprimé 2 fois par jour pendant les repas',
    defaultDuration: 'Traitement continu',
    defaultInstructions: 'Prendre pendant les repas.',
    contraindications: 'Insuffisance rénale sévère, acidocétose.',
    unitPrice: 48.0,
    presentation: 'Boîte de 30 comprimés',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_89',
    name: 'Diamicron MR 60 mg',
    dci: 'Gliclazide',
    dosage: '60 mg',
    category: 'Antidiabétique oral / Sulfamide hypoglycémiant',
    dosageForm: 'Comprimé sécable à libération modifiée',
    laboratory: 'Servier Maroc',
    defaultDosage: '1/2 à 2 comprimés en 1 seule prise par jour au petit-déjeuner',
    defaultDuration: 'Traitement chronique',
    defaultInstructions: 'Prendre impérativement au moment du petit-déjeuner. Ne jamais sauter le repas après la prise (risque d’hypoglycémie).',
    contraindications: 'Diabète de type 1, acidocétose, insuffisance rénale ou hépatique sévère, allaitement.',
    sideEffects: 'Hypoglycémie (sueurs, tremblements, fringale, pâleur).',
    unitPrice: 84.0,
    presentation: 'Boîte de 30 comprimés sécables MR',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_90',
    name: 'Januvia 100 mg',
    dci: 'Sitagliptine',
    dosage: '100 mg',
    category: 'Antidiabétique oral / Inhibiteur DPP-4 (Gliptine)',
    dosageForm: 'Comprimé pelliculé',
    laboratory: 'MSD / Maphar Maroc',
    defaultDosage: '1 comprimé par jour en 1 prise à n’importe quel moment de la journée',
    defaultDuration: 'Traitement chronique',
    defaultInstructions: 'Peut être pris au cours ou en dehors des repas.',
    contraindications: 'Hypersensibilité à la sitagliptine, antécédent de pancréatite aiguë.',
    unitPrice: 195.0,
    presentation: 'Boîte de 28 comprimés',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_91',
    name: 'Jardiance 10 mg',
    dci: 'Empagliflozine',
    dosage: '10 mg',
    category: 'Antidiabétique oral / Inhibiteur SGLT-2 (Gliflozine)',
    dosageForm: 'Comprimé pelliculé',
    laboratory: 'Boehringer Ingelheim Maroc',
    defaultDosage: '1 comprimé par jour le matin avec un verre d’eau',
    defaultDuration: 'Traitement au long cours (diabète T2 / insuffisance cardiaque)',
    defaultInstructions: 'Assurer une bonne hydratation quotidienne. Surveiller l’hygiène génitale (risque d’infections fongiques mycosiques).',
    contraindications: 'DFG < 20 ml/min, acidocétose diabétique.',
    unitPrice: 280.0,
    presentation: 'Boîte de 30 comprimés',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_92',
    name: 'Levothyrox 50 µg',
    dci: 'Lévothyroxine sodique',
    dosage: '50 µg',
    category: 'Hormone thyroïdienne / Endocrinologie',
    dosageForm: 'Comprimé sécable',
    laboratory: 'Merck Serono / Cooper Pharma Maroc',
    defaultDosage: '1 comprimé par jour le matin strictement à jeun 30 minutes avant le petit-déjeuner',
    defaultDuration: 'Traitement substitutif à vie',
    defaultInstructions: 'Prendre avec un peu d’eau au réveil en restant à jeun 30 minutes. Ne pas prendre de calcium ni de fer en même temps.',
    contraindications: 'Thyréotoxicose non traitée, insuffisance surrénalienne non compensée, infarctus récent.',
    unitPrice: 17.5,
    presentation: 'Boîte de 30 comprimés sécables',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_93',
    name: 'Levothyrox 100 µg',
    dci: 'Lévothyroxine sodique',
    dosage: '100 µg',
    category: 'Hormone thyroïdienne / Endocrinologie',
    dosageForm: 'Comprimé sécable',
    laboratory: 'Merck Serono / Cooper Pharma Maroc',
    defaultDosage: '1 comprimé le matin strictement à jeun 30 minutes avant le repas',
    defaultDuration: 'Traitement à vie',
    defaultInstructions: 'Prise stricte à jeun le matin. Contrôle TSH tous les 6 à 12 mois.',
    contraindications: 'Thyréotoxicose décompensée.',
    unitPrice: 22.0,
    presentation: 'Boîte de 30 comprimés sécables',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },

  // ==========================================
  // NEURO-PSYCHIATRIE & ANXIOLYTIQUES
  // ==========================================
  {
    id: 'mar_med_94',
    name: 'Lexomil 6 mg',
    dci: 'Bromazépam',
    dosage: '6 mg',
    category: 'Anxiolytique / Benzodiazépine (Tableau A)',
    dosageForm: 'Comprimé baguette quadrisécable',
    laboratory: 'Roche / Maphar Maroc',
    defaultDosage: '1/4 de comprimé matin et midi, et 1/2 comprimé le soir au coucher (ajuster selon anxiété)',
    defaultDuration: '2 à 4 semaines maximum (sevrage progressif obligatoire)',
    defaultInstructions: 'Durée de prescription limitée. Ne pas interrompre brutalement. Éviter toute boisson alcoolisée.',
    contraindications: 'Insuffisance respiratoire sévère, myasthénie, apnée du sommeil, insuffisance hépatique décompensée.',
    sideEffects: 'Somnolence, baisse de vigilance, dépendance physique et psychique.',
    unitPrice: 26.5,
    presentation: 'Boîte de 30 comprimés baguette quadrisécables',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_95',
    name: 'Xanax 0.5 mg',
    dci: 'Alprazolam',
    dosage: '0.5 mg',
    category: 'Anxiolytique / Benzodiazépine (Tableau A)',
    dosageForm: 'Comprimé sécable',
    laboratory: 'Pfizer Maroc',
    defaultDosage: '1/2 à 1 comprimé 2 à 3 fois par jour',
    defaultDuration: 'Court terme (2 à 4 semaines max)',
    defaultInstructions: 'Respecter les doses. Risque d’accoutumance.',
    contraindications: 'Insuffisance respiratoire, myasthénie grave.',
    unitPrice: 28.0,
    presentation: 'Boîte de 30 comprimés sécables',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_96',
    name: 'Stilnox 10 mg (Zolpidem)',
    dci: 'Zolpidem hémitartrate',
    dosage: '10 mg',
    category: 'Hypnotique / Sédatif apparenté BZD',
    dosageForm: 'Comprimé pelliculé sécable',
    laboratory: 'Sanofi-Aventis Maroc',
    defaultDosage: '1 comprimé immédiatement avant le coucher au lit (1/2 comprimé chez le sujet âgé)',
    defaultDuration: 'Quelques jours à 2 semaines max',
    defaultInstructions: 'Prendre juste au moment de se mettre au lit. Assurer au moins 8 heures de sommeil consécutif.',
    contraindications: 'Insuffisance respiratoire sévère, apnée du sommeil, myasthénie.',
    unitPrice: 38.5,
    presentation: 'Boîte de 14 comprimés',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_97',
    name: 'Seroplex 10 mg (Escitalopram)',
    dci: 'Escitalopram oxalate',
    dosage: '10 mg',
    category: 'Antidépresseur / ISRS',
    dosageForm: 'Comprimé pelliculé sécable',
    laboratory: 'Lundbeck / Maphar Maroc',
    defaultDosage: '1 comprimé par jour en 1 prise le matin ou le soir',
    defaultDuration: 'Traitement de 6 mois minimum pour consolidation',
    defaultInstructions: 'L’effet thérapeutique apparaît après 2 à 3 semaines de prise régulière. Ne pas interrompre brutalement.',
    contraindications: 'Association aux IMAO non sélectifs, allongement congénital du QT.',
    unitPrice: 118.0,
    presentation: 'Boîte de 28 comprimés sécables',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_98',
    name: 'Laroxyl 25 mg',
    dci: 'Amitriptyline',
    dosage: '25 mg',
    category: 'Antidépresseur imipraminique / Douleurs neuropathiques',
    dosageForm: 'Comprimé pelliculé',
    laboratory: 'Roche / Maphar Maroc',
    defaultDosage: '1 comprimé le soir au coucher (augmenter très progressivement)',
    defaultDuration: 'Selon indication',
    defaultInstructions: 'Prise le soir au coucher en raison de l’effet sédatif marqué.',
    contraindications: 'Glaucome à angle fermé, risque de rétention urinaire (adénome prostatique), infarctus récent.',
    unitPrice: 26.0,
    presentation: 'Boîte de 20 comprimés',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },

  // ==========================================
  // VITAMINES, MINÉRAUX & SUPPLÉMENTS
  // ==========================================
  {
    id: 'mar_med_99',
    name: 'D-Cure 100 000 UI Ampoule Buvable',
    dci: 'Cholécalciférol (Vitamine D3)',
    dosage: '100 000 UI',
    category: 'Vitamine D / Métabolisme phosphocalcique',
    dosageForm: 'Solution buvable en ampoule',
    laboratory: 'SMB / Laprophan Maroc',
    defaultDosage: '1 ampoule buvable par mois ou tous les 2 à 3 mois selon déficit biologique',
    defaultDuration: 'Selon taux de 25-OH-Vitamine D',
    defaultInstructions: 'Casser l’ampoule et boire le contenu directement ou mélangé à une cuillère de yaourt ou d’huile.',
    contraindications: 'Hypercalcémie, hypercalciurie, lithiase rénale calcique.',
    unitPrice: 28.5,
    presentation: 'Boîte de 1 ampoule buvable de 2 ml',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_100',
    name: 'Sterogyl 2 000 000 UI Gouttes',
    dci: 'Ergocalciférol (Vitamine D2)',
    dosage: '400 UI par goutte',
    category: 'Vitamine D pédiatrique',
    dosageForm: 'Solution buvable en flacon compte-gouttes',
    laboratory: 'DBS / Cooper Pharma Maroc',
    defaultDosage: '2 à 4 gouttes par jour chez le nourrisson et l’enfant',
    defaultDuration: 'Supplémentation quotidienne',
    defaultInstructions: 'Administrer dans une cuillère avec un peu de liquide ou pur.',
    contraindications: 'Hypercalcémie, lithiase calcique.',
    unitPrice: 22.0,
    presentation: 'Flacon compte-gouttes de 20 ml',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_101',
    name: 'Tardyferon B9',
    dci: 'Fer sesquioxyde + Acide folique (Vitamine B9)',
    dosage: '50 mg de fer / 0.35 mg d’acide folique',
    category: 'Antianémique martial / Grossesse',
    dosageForm: 'Comprimé enrobé',
    laboratory: 'Pierre Fabre Maroc',
    defaultDosage: '1 comprimé par jour avant ou pendant les repas',
    defaultDuration: '3 à 6 mois',
    defaultInstructions: 'Prendre avec un verre d’eau ou de jus d’orange (la vitamine C favorise l’absorption). Les selles peuvent être colorées en noir.',
    contraindications: 'Surcharge martiale (hémochromatose, thalassémie).',
    sideEffects: 'Constipation, nausées passagères, coloration noire des selles.',
    unitPrice: 38.5,
    presentation: 'Boîte de 30 comprimés',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_102',
    name: 'Fumafer 66 mg',
    dci: 'Fumarate ferreux',
    dosage: '66 mg de fer élément',
    category: 'Antianémique martial',
    dosageForm: 'Comprimé pelliculé',
    laboratory: 'Sanofi-Aventis Maroc',
    defaultDosage: '1 à 2 comprimés par jour avant les repas',
    defaultDuration: '3 à 6 mois',
    defaultInstructions: 'Prendre de préférence à distance du thé et du café.',
    contraindications: 'Hémochromatose, anémies non ferriprives.',
    unitPrice: 24.0,
    presentation: 'Boîte de 30 comprimés',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_103',
    name: 'Mag 2 Ampoules Buvables',
    dci: 'Magnésium élément',
    dosage: '100 mg / 10 ml',
    category: 'Supplémentation en magnésium / Spasmophilie',
    dosageForm: 'Solution buvable en ampoules autocassables',
    laboratory: 'Cooper / Sanofi Maroc',
    defaultDosage: '1 ampoule 2 à 3 fois par jour au cours des repas dans un demi-verre d’eau',
    defaultDuration: '1 mois',
    defaultInstructions: 'Prendre pendant les repas.',
    contraindications: 'Insuffisance rénale sévère (clairance < 30 ml/min).',
    unitPrice: 36.0,
    presentation: 'Boîte de 30 ampoules de 10 ml',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_104',
    name: 'Supradyn Intensia',
    dci: 'Polyvitamines + Minéraux + Oligo-éléments',
    dosage: 'Multi-vitamines + Coenzyme Q10',
    category: 'Tonique général / Polyvitamines',
    dosageForm: 'Comprimé pelliculé / effervescent',
    laboratory: 'Bayer Maroc',
    defaultDosage: '1 comprimé par jour le matin au petit-déjeuner',
    defaultDuration: '30 jours',
    defaultInstructions: 'Prendre avec un grand verre d’eau le matin.',
    contraindications: 'Hypervitaminose A ou D, insuffisance rénale sévère.',
    unitPrice: 65.0,
    presentation: 'Boîte de 30 comprimés',
    reimbursementRate: 'Non remboursable',
    isPreloaded: true,
    isActive: true,
  },

  // ==========================================
  // DERMATOLOGIE & LOCAL
  // ==========================================
  {
    id: 'mar_med_105',
    name: 'Fucidine 2% Crème',
    dci: 'Acide fusidique',
    dosage: '2%',
    category: 'Antibiotique topique / Dermatologie',
    dosageForm: 'Crème dermique',
    laboratory: 'LEO Pharma / Maphar Maroc',
    defaultDosage: '1 application locale 2 à 3 fois par jour après nettoyage de la lésion',
    defaultDuration: '7 jours',
    defaultInstructions: 'Appliquer en couche mince avec ou sans pansement protecteur.',
    contraindications: 'Hypersensibilité à l’acide fusidique.',
    unitPrice: 36.5,
    presentation: 'Tube de 15 g',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_106',
    name: 'Fucidine 2% Pommade',
    dci: 'Fusidate de sodium',
    dosage: '2%',
    category: 'Antibiotique topique / Dermatologie',
    dosageForm: 'Pommade dermique',
    laboratory: 'LEO Pharma / Maphar Maroc',
    defaultDosage: '1 à 2 applications par jour (lésions sèches, croûteuses ou impétigo)',
    defaultDuration: '7 jours',
    defaultInstructions: 'Convient particulièrement aux lésions sèches.',
    contraindications: 'Allergie aux fusidates.',
    unitPrice: 36.5,
    presentation: 'Tube de 15 g',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_107',
    name: 'Diprosone 0.05% Crème',
    dci: 'Bétaméthasone dipropionate',
    dosage: '0.05%',
    category: 'Dermocorticoïde d’activité forte (Classe II)',
    dosageForm: 'Crème dermique',
    laboratory: 'Organon / Maphar Maroc',
    defaultDosage: '1 application par jour en couche mince suivie d’un léger massage',
    defaultDuration: '5 à 10 jours (diminuer progressivement)',
    defaultInstructions: 'Ne pas appliquer sur le visage sans avis médical strict. Ne pas utiliser sous pansement occlusif.',
    contraindications: 'Lésions ulcérées, acné, rosacée, infections cutanées bactériennes ou virales primitives.',
    unitPrice: 32.0,
    presentation: 'Tube de 30 g',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_108',
    name: 'Dermoval 0.05% Crème',
    dci: 'Clobétasol propionate',
    dosage: '0.05%',
    category: 'Dermocorticoïde d’activité très forte (Classe I)',
    dosageForm: 'Crème dermique',
    laboratory: 'GlaxoSmithKline (GSK) Maroc',
    defaultDosage: '1 application par jour en couche mince sur les plaques rebelles (psoriasis/lichen)',
    defaultDuration: 'Courte durée (1 à 2 semaines max)',
    defaultInstructions: 'Application très ciblée. Ne jamais appliquer sur le visage.',
    contraindications: 'Infections cutanées non traitées, acné, rosacée, enfant de moins de 1 an.',
    unitPrice: 38.0,
    presentation: 'Tube de 30 g',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_109',
    name: 'Betadine Dermique 10%',
    dci: 'Povidone iodée',
    dosage: '10%',
    category: 'Antiseptique local à large spectre',
    dosageForm: 'Solution pour application locale (Flacon jaune)',
    laboratory: 'Mundipharma / Cooper Pharma Maroc',
    defaultDosage: 'Application pure ou diluée au 1/10ème sur la peau saine ou lésée',
    defaultDuration: 'Usage ponctuel lors des soins',
    defaultInstructions: 'Ne jamais associer aux dérivés mercuriels (risque de composé caustique).',
    contraindications: 'Antécédent d’allergie à la povidone iodée, nouveau-né prématuré, grossesse (usage répété).',
    unitPrice: 18.0,
    presentation: 'Flacon de 125 ml',
    reimbursementRate: 'Non remboursable',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_110',
    name: 'Cicatryl Pommade',
    dci: 'Allantoïne + Vitamine E + Chlorcrésol',
    dosage: 'Complexe cicatrisant',
    category: 'Cicatrisant local protecteur',
    dosageForm: 'Pommade en sachets unidoses',
    laboratory: 'Pierre Fabre Dermatologie Maroc',
    defaultDosage: '1 application 1 à 2 fois par jour sur la plaie nettoyée',
    defaultDuration: '5 à 7 jours',
    defaultInstructions: 'Masser légèrement pour faire pénétrer.',
    contraindications: 'Lésions surinfectées.',
    unitPrice: 28.0,
    presentation: 'Boîte de 14 sachets de 2 g',
    reimbursementRate: 'Non remboursable',
    isPreloaded: true,
    isActive: true,
  },

  // ==========================================
  // OPHTALMOLOGIE & GYNÉCOLOGIE
  // ==========================================
  {
    id: 'mar_med_111',
    name: 'Tobrex Collyre 0.3%',
    dci: 'Tobramycine',
    dosage: '0.3%',
    category: 'Antibactérien ophtalmique / Aminoside',
    dosageForm: 'Collyre en solution',
    laboratory: 'Novartis Pharma / Alcon Maroc',
    defaultDosage: '1 à 2 gouttes dans le cul-de-sac conjonctival 4 à 6 fois par jour',
    defaultDuration: '5 à 7 jours',
    defaultInstructions: 'Instiller en tirant la paupière inférieure vers le bas. Jeter le flacon 28 jours après ouverture.',
    contraindications: 'Allergie aux aminosides.',
    unitPrice: 26.5,
    presentation: 'Flacon compte-gouttes de 5 ml',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_112',
    name: 'Chibro-Cadron Collyre',
    dci: 'Dexaméthasone + Néomycine',
    dosage: 'Corticoïde + Antibiotique ophtalmique',
    category: 'Anti-inflammatoire et antibactérien ophtalmique',
    dosageForm: 'Collyre en solution',
    laboratory: 'Théa / Laprophan Maroc',
    defaultDosage: '1 goutte 3 à 4 fois par jour dans l’œil atteint',
    defaultDuration: '5 à 7 jours sous contrôle ophtalmique',
    defaultInstructions: 'Ne pas dépasser la durée prescrite (risque d’hypertonie oculaire).',
    contraindications: 'Kératite herpétique ou mycosique (ulcère cornéen), glaucome.',
    unitPrice: 32.0,
    presentation: 'Flacon compte-gouttes de 5 ml',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_113',
    name: 'Gyno-Pevaryl 150 mg Ovules',
    dci: 'Éconazole nitrate',
    dosage: '150 mg',
    category: 'Antimycosique gynécologique',
    dosageForm: 'Ovule vaginal',
    laboratory: 'Janssen-Cilag / Johnson & Johnson Maroc',
    defaultDosage: '1 ovule au coucher pendant 3 jours consécutifs au fond du vagin',
    defaultDuration: '3 jours',
    defaultInstructions: 'Introduire profondément l’ovule en position allongée le soir. Ne pas interrompre pendant les règles.',
    contraindications: 'Allergie aux dérivés imidazolés.',
    unitPrice: 34.5,
    presentation: 'Boîte de 3 ovules vaginaux',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
  {
    id: 'mar_med_114',
    name: 'Polygynax Capsules Vaginales',
    dci: 'Néomycine + Polymyxine B + Nystatine',
    dosage: 'Antibactérien + Antifongique local',
    category: 'Traitement des vaginites mixtes',
    dosageForm: 'Capsule vaginale molle',
    laboratory: 'Innotech / Maphar Maroc',
    defaultDosage: '1 capsule le soir au coucher au fond du vagin pendant 6 à 12 jours',
    defaultDuration: '6 à 12 jours',
    defaultInstructions: 'Prise vespérale en position allongée.',
    contraindications: 'Allergie aux composants ou au soja/arachide.',
    unitPrice: 48.0,
    presentation: 'Boîte de 6 ou 12 capsules vaginales',
    reimbursementRate: 'Remboursable AMO (70%)',
    isPreloaded: true,
    isActive: true,
  },
];
